// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

const SUPABASE_URL = 'https://omcxfssocuehoiylewtj.supabase.co'
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tY3hmc3NvY3VlaG9peWxld3RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTI0MDgsImV4cCI6MjA2NjYyODQwOH0.hiGJhDGgtCg7iRQ7QJRHN4cC77GPDnpKRATopJx5QAU'

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const authOptions =
  typeof localStorage !== 'undefined'
    ? {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    : {
        persistSession: false,
        autoRefreshToken: false,
      }

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: authOptions,
  },
)
